---
- name: Configuring Apache Server 
  hosts: all
  tasks:
  - name: Installation of Apache server package
    yum: 
     name: httpd
     state: present 

  - name: Create Index File 
    copy: 
     content: "Hello Fidelity!! This is Ansible Automation Here!!"
     dest: /var/www/html/index.html 

  - name: Starting  The Service 
    service: 
     name: httpd
     state: started 
     enabled: yes

  - name: Enable the Firewall
    firewalld: 
     service: http
     immediate: true
     permanent: yes
     state: enabled 
